version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - minecraft_network
    environment:
      - MINECRAFT_SERVER_HOST=${MINECRAFT_SERVER_HOST}
      - MINECRAFT_SERVER_RCON_PORT=${MINECRAFT_SERVER_RCON_PORT:-25575}
      - MINECRAFT_SERVER_RCON_PASSWORD=${MINECRAFT_SERVER_RCON_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  minecraft_network:
    external: true